name: Run test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Upgrade setuptools
        run: |
          pip install --upgrade setuptools
      - name: Run tests
        run: python setup.py test
